### ISSUE TITLE
lanes.threads() bad status

### ISSUE THREAD

**Issue by sonoro1234** [LuaLanes/lanes#182] opened 2020-06-12 15:17 UTC
Hello,

I am using `set_debug_threadname` in lanes creation and `track_lanes` on configure.
There is a lane that I generate several times, after it is done it does not change its status (got with lanes.threads()) when I generate it again. (Althought I can check that it is running again)

If in lane creation I give a different debug_threadname each time (with a counter) then I get the correct status with `lanes.threads` but the already done lanes continue appearing (with status done) in the table returned by `lanes.threads`.

**Comment by benoit-germain** [comment] 2021-06-16 16:10
The problem is that I populate a table indexed by the lane's name. Thus, when iterating over the lanes, if several have the same name, you will have the status of the one that was created first (because tracking inserts the lanes at the head of a single-linked list, so I process them in reverse creation order). To fix that I will have to change the output of ``lanes.threads()``.

**Comment by benoit-germain** [comment] 2021-06-16 16:42
Fixed by 5875fe44ba7a240dd101f954c7dc83337a0c2cef

**Closed by benoit-germain** 2021-06-16 16:42 UTC
